1) define your exception class by name "MyArithException"
(MyArithException.java)
define class "Calculator"   (Calculator.java)
In this class define a function,which will accept an int and return double of it.
e.g int caldouble(int)
This function will check an int which is passed to it
It will raise the  exception if 0 is passed or negative passed
in case of 0 caller of this method should get error message
"Zero not allowed" 
in case of negative caller of this method should get error message
"negative not allowed"
In case of positive value it should simply return the double value.
	[ this method shouldn't handle the exception]

Now define class "MyCalcApp" (MyCalcApp.java)
In this class you accept a number from user and pass that no. to
caldouble() method which is mentioned above.


2) on the developer side create an exception:
	NumberNotDivisibleBySevenException
	as a checked exception

create necessary jar and documentation.

on client side
	public class MyMath class with 
		public void disp(int num)
this disp() method will check if the number passed is not divisible by 7 , it will raise "NumberNotDivisibleBySevenException" or else it will simply display the number passed.
	[ this method shouldn't handle the exception]

	public class Demo
		main function 
		invoke "disp()" of "MyMath" class.

3) define "MyException" as a checked exception.

define a class "Demo" with 
	public void show1(), public void show2() , public void show3() and main functions.

inside "show3()" accept a number and if it is greater than 10 raise "MyException" else display the number.
	[ this method shouldn't handle the exception]

main() function should call "show1()" , 
show1() function should call "show2()",
show2() function should call "show3()"

show2() should not handle the exception but show1() should handle.

4) on the developer side create following checked exception:
	InvalidLengthException
create necessary jar file and documentation.

on client side

public class Authenticator
	with
a parameterized constructor which takes String as a password.
this class also will have "done()" method with "successful authentication" message.
Parameterized constructor should check the length of the password passed if it is less than 5 or more that 9 , it should raise "InvalidLengthException" 
	[ constructor shouldn't handle the exception]

create a class "Demo" with main
	inside main function create the object of "Authenticator" class and invoke "done()" method.

5) on the developer side 
create checked exception "ResourceNotAllocatedException"

create a class:

public class MyResource implements AutoCloseable
{
	public MyResource(int capacity) throws ResourceNotAllocatedException
	{
		if(capacity>100)
		{
			throw new ResourceNotAllocatedException("not sufficient space");
		}
	}
    void disp()
    {
    	System.out.println("successful");
    }
	@Override
	public void close()  {
		System.out.println("resource is closed");
		
	}
}

create necessary jar file and documentation

on the client side
public class Demo with main function

	inside main function, create object of "

" and invoke "disp()" method.

Answers:
//q1
package q1;

public class MyArithException extends Exception
{
	MyArithException(String msg)
	{
		super(msg);
	}
}
package q1;

public class Calculator 
{
	int num;
	public int cal(int num) throws MyArithException
	{
		int res = num+num;
		if(num<=0)
		{
			throw new MyArithException("Zero and negative numbers are not allowed") ;
		}
		else
			return res;
			
	}
	
}
package q1;

import java.util.Scanner;

public class MyCalcApp 
{

	public static void main(String[] args) throws MyArithException 
	{
		Scanner sc = new Scanner(System.in);
		System.out.println("enter a number");
		int num = sc.nextInt();
		Calculator c = new Calculator();
		int d = c.cal(num);
		System.out.println("number is "+num);
		System.out.println("number after double is "+ d);
	}

}


//q2
package devpack;

public class NumberNotDivisibleBySevenException extends Exception
{
	public NumberNotDivisibleBySevenException(String msg)
	{
		super(msg);
	}
}

package clienrPack;

import devpack.NumberNotDivisibleBySevenException;

public class MyMath 
{
	public void disp(int num) throws NumberNotDivisibleBySevenException
	{
		if(num% 7 !=0)
		{
			throw new NumberNotDivisibleBySevenException("NumberNotDivisibleBySevenException");
		}
		else
			System.out.println("num is divisible by 7");
	}

}

package clienrPack;

import java.util.Scanner;

import devpack.NumberNotDivisibleBySevenException;

public class Main 
{
	public static void main(String[] args) throws NumberNotDivisibleBySevenException
	{
		MyMath m = new MyMath();
		int num;
		System.out.println("enter a number");
		Scanner sc = new Scanner(System.in);
		num=sc.nextInt();
		m.disp(num);

	}


}

//q3
package q3;

public class MyException extends Exception
{
	MyException(String msg)
	{
		super(msg);
	}

}
package q3;
import java.util.Scanner;
public class Demo 
{
	int num;
	Scanner sc = new Scanner(System.in);
	public void show1()throws MyException
	{
		try
		{
			show2();
		}
		catch(MyException e)
		{
			e.printStackTrace();
		}
	}
	public void show2()throws MyException
	{
		
		show3();
	}
	public void show3() throws MyException
	{
		System.out.println("enter a num");
		num = sc.nextInt();
		
		if(num>10) 
		{
			throw new MyException("MyException");
		}
		else
			System.out.println("num is "+num);
	}
	public static void main(String ...args) throws MyException
	{
		Demo d = new Demo();
		d.show1();
	}
}

//q4
package devPack;

public class InvalidLengthException extends Exception
{
	public InvalidLengthException(String msg)
	{
		super(msg);
	}
}
package clientpack;

import devPack.InvalidLengthException;

public class Authenticator 
{
	private String password;
	
	public Authenticator(String password)throws InvalidLengthException
	{
		this.password=password;
		if(password.length()<5 || password.length()>9) 
		{
			throw new InvalidLengthException("InvalidLengthException");
		}
	}
	public void done()
	{
		System.out.println("successful authentication");
	}

}
package clientpack;

import devPack.InvalidLengthException;

public class Demo
{

	public static void main(String[] args) throws InvalidLengthException 
	{
		Authenticator a = new Authenticator("230297");
		a.done();

	}

}


//q5
package devpack;

public class MyResource implements AutoCloseable 
{
	public MyResource(int capacity) throws ResourceNotAllocatedException
	{
		if(capacity>100)
		{
			throw new ResourceNotAllocatedException("not sufficient space");
		}
	}
    public void disp()
    {
    	System.out.println("successful");
    }
	@Override
	public void close()  
	{
		System.out.println("resource is closed");
		
	}

}
package devpack;

public class ResourceNotAllocatedException extends Exception
{

	public ResourceNotAllocatedException(String msg)
	{
		super(msg);
	}
}
package clientpro;

import devpack.MyResource;
import devpack.ResourceNotAllocatedException;

public class Demo 
{

	public static void main(String[] args) throws ResourceNotAllocatedException 
	{
		MyResource m = new MyResource(26);
		m.disp();

	}

}